# Generated by Django 3.1 on 2020-08-10 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_auto_20200806_2241'),
        ('userprofile', '0005_auto_20200810_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='favorites',
            field=models.ManyToManyField(to='recipe.Recipe'),
        ),
    ]
