# Generated by Django 2.2.12 on 2020-08-11 04:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_auto_20200810_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='favorites',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
