# Generated by Django 2.2.12 on 2020-08-11 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0008_auto_20200811_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='favorites',
            field=models.ManyToManyField(related_name='favorited_by', to='recipe.Recipe'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
    ]
