# Generated by Django 2.2.12 on 2020-06-01 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='details',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='post',
            name='ingredients',
        ),
    ]
