# Generated by Django 2.2.12 on 2020-06-01 03:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_auto_20200531_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cooktime',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
